server:
  port: 9091

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@54.180.8.49:1521:XE
    username: freecommu
    password: 1234

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  thymeleaf:
    prefix: classpath:templates/
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace